export const GET_USERS_DATA = 'GET_USERS_DATA';
export const GET_USERS_DATA_LOADING = 'GET_USERS_DATA_LOADING';
export const GET_USERS_DATA_FAILURE = 'GET_USERS_DATA_FAILURE';
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
export const RESET_DATA = 'RESET_DATA';
